### ISSUE TITLE
Can't set default tiling mode

### ISSUE THREAD

**Issue by cparadis6191** [ZaneA/HashTWM#15]
I can't seem to set the default tiling mode with the -t flag regardless of where I launch the program (cmd.exe or a mintty bash shell or a startup service). I can change the tiling mode with mod + space but the default doesn't seem to work. Here's an example of my usage:

hashtwm.exe -t 2 -a mintty

Thanks for any help.

**Comment by ZaneA** [comment]
Hey Chad, I think this was broken in a previous commit, could you try the updated source/binary and see if that fixes it? Seems to work for me now.

**Comment by cparadis6191** [comment]
Yep, that fixes it for me. Thanks for the quick response! I found another simple problem concerning toggling tiling modes but I'll make a new issue for it when I get a chance.
