### ISSUE TITLE
Mod + space doesn't cycle through all available tiling modes

### ISSUE THREAD

**Issue by cparadis6191** [ZaneA/HashTWM#16]
There are four tiling modes listed in the README.md: vertical, horizontal, grid, and fullscreen. These can all be accessed with the -t flag but when cycling with the mod + space binding it only cycles through three of them (fullscreen can't be accessed by cycling). 

[This](https://github.com/ZaneA/HashTWM/blob/master/src/main.c#L638) line with the modulo looks to me to be the problem. Changing that to a four should fix it. I'm assuming this problem popped up when a new tiling mode was added so a better way to fix it might be something like the following:

```C
// Tiling modes
enum tiling_modes {
  MODE_VERTICAL = 0,
  MODE_HORIZONTAL,
  MODE_GRID,
  MODE_FULLSCREEN,
  // Keep this at the end if adding tiling modes
  MODE_END
};
```

and changing the modulo to

```C
tags[current_tag].tilingMode = (tags[current_tag].tilingMode + 1) % (MODE_END - 1);
```

This way adding or removing a tiling mode won't break cycling. I'd do a pull request but I don't have the compiler set up so I can't test it properly. Thanks for your time.

**Comment by ZaneA** [comment]
Hey, sorry I'm horrendous at maintaining my repos! I've implemented your fix above, though had to use `MODE_END` as opposed to `(MODE_END - 1)`. But now it is possible to switch to fullscreen mode as intended. Thanks for your help :)
