### ISSUE TITLE
Have the main areacentered

### ISSUE THREAD

**Issue by marvin-bitterlich** [ZaneA/HashTWM#20]
At the moment, the main area is always to the side. Would it be possible to have a mode, where the main area is in the center and side windows get sorted to both sides? Would be a nice addition for 4k monitors :)

**Comment by ZaneA** [comment]
This would be a cool feature :) how do you think Window movement would work? windows on the left being "above" the main window, and windows on the right being "below"?

**Comment by Kostronor** [comment]
The way I would like to have it would be having two separate stacks. 
You have a command to push windows from left to right and back. You can puch windows up and down the stack. And you can push them in the middle, switching places with the current middle window. 

Make it like a triangle, both sides are below the middle, they can move on level or rise up to the middle. (and move inside their stack)

**Comment by prail** [comment]
@reggaemuffin Does this image look somewhat like you've described? I'm not sure I understood your comments about the triangle part well though.
![Mock-up of main window with stacks.](https://user-images.githubusercontent.com/16790483/48985733-e408c580-f0bf-11e8-9969-bc73f81552b9.png)
The commands to move things left and right would pull windows out of the left/right stacks and into the main viewing area in the center, correct?

**Comment by reggaemuffin** [comment]
Yes, something like that would be great!
