### ISSUE TITLE
Why are the file signatures in the project folder, and bin folder different?

### ISSUE THREAD

**Issue by ipstone** [ZaneA/HashTWM#27]
md5sum
Project folder:   f8243a3f2473bfb1b13a3db9ea2dca66 *hashtwm.exe
bin subfoloder: 0ebf9b43e4a3685a1a391daded34c348 *hashtwm.exe

They should be the same, right?

**Comment by ZaneA** [comment]
Yup, I'd missed that sorry, it looks like the one from the bin subfolder is a few days older, so the project folder one is the latest.

**Comment by ipstone** [comment]
Thanks! I am closing the issue now.
